defmodule MyDevice.DeviceTest do
  @moduledoc """
  Host-side unit tests for `MyDevice.Device`.

  Exercises the static shape of the SootDevice DSL module: the
  generated `__soot_device_opts__/0` reflects the compile-time
  options, `child_spec/1` returns a valid Supervisor child spec, and
  `MyDevice.SootDeviceConfig.device_opts/1` reads from the operator's
  application env.

  These tests run in `mix test` without QEMU. The QEMU integration
  variant lives in `qemu_test.exs` and is gated on `:qemu`.

  Generated by `mix soot_device.gen.tests`. Operators own this file;
  re-running the generator will not overwrite it.
  """

  use ExUnit.Case, async: true

  alias MyDevice.Device

  describe "DSL module shape" do
    test "exposes __soot_device_opts__/0 with contract_url, enroll_url, and serial" do
      opts = Device.__soot_device_opts__()
      assert is_list(opts)
      assert is_binary(Keyword.fetch!(opts, :contract_url))
      assert is_binary(Keyword.fetch!(opts, :enroll_url))
      assert is_binary(Keyword.fetch!(opts, :serial))
    end

    test "exports child_spec/1, child_specs/1, and start_link/1" do
      assert function_exported?(Device, :child_spec, 1)
      assert function_exported?(Device, :child_specs, 1)
      assert function_exported?(Device, :start_link, 1)
    end

    test "child_spec/1 returns a Supervisor-shaped map" do
      spec = Device.child_spec([])
      assert is_map(spec)
      assert Map.has_key?(spec, :id)
      assert Map.has_key?(spec, :start)
    end
  end

  describe "config helper" do
    setup do
      previous =
        for key <- [
              :contract_url,
              :enroll_url,
              :serial,
              :operational_storage,
              :persistence_dir
            ],
            into: %{} do
          {key, Application.get_env(:my_device, key)}
        end

      Application.put_env(:my_device, :contract_url, "https://test.local/.well-known/soot/contract")
      Application.put_env(:my_device, :enroll_url, "https://test.local/enroll")
      Application.put_env(:my_device, :serial, "TEST-SERIAL-0001")
      Application.put_env(:my_device, :operational_storage, :memory)
      Application.put_env(:my_device, :persistence_dir, System.tmp_dir!())

      on_exit(fn ->
        for {key, value} <- previous do
          if is_nil(value),
            do: Application.delete_env(:my_device, key),
            else: Application.put_env(:my_device, key, value)
        end
      end)

      :ok
    end

    test "device_opts/1 reads contract_url, enroll_url, and serial from app env" do
      opts = MyDevice.SootDeviceConfig.device_opts()
      assert Keyword.fetch!(opts, :contract_url) == "https://test.local/.well-known/soot/contract"
      assert Keyword.fetch!(opts, :enroll_url) == "https://test.local/enroll"
      assert Keyword.fetch!(opts, :serial) == "TEST-SERIAL-0001"
    end

    test "device_opts/1 lets caller-supplied overrides win" do
      opts = MyDevice.SootDeviceConfig.device_opts(serial: "OVERRIDDEN")
      assert Keyword.fetch!(opts, :serial) == "OVERRIDDEN"
    end

    test "fetch!/1 raises when the key is unset" do
      Application.delete_env(:my_device, :contract_url)

      assert_raise RuntimeError, ~r/missing :my_device config key :contract_url/, fn ->
        MyDevice.SootDeviceConfig.fetch!(:contract_url)
      end
    end
  end
end
