defmodule MyDevice.QEMU do
  @moduledoc """
  Boots a Nerves QEMU image and connects to it over Erlang distribution
  so the host-side test process can drive it via `:rpc.call/4`.

  Generated by `mix soot_device.gen.tests`. Operator owns this file
  post-install — the framework does not re-touch it.

  ## How it works

    1. Locate a `qemu_aarch64` Nerves firmware image under
       `_build/qemu_aarch64_*/nerves/images/`.
    2. Launch `qemu-system-aarch64` with user-mode networking and
       hostfwd port forwards for EPMD (4369) and the pinned
       distribution port (9100).
    3. Poll `Node.connect/1` until the device's node registers.
    4. Return a handle that callers can pass to `rpc/4` and `stop/1`.

  User-mode networking (`-netdev user`) needs no special privileges,
  so this works on developer laptops, CI runners, and Docker hosts
  alike. The trade-off: the device cannot reach the host's
  `localhost`. Test backends that need callbacks should bind
  `0.0.0.0` and use the QEMU gateway IP `10.0.2.2`.

  ## Tagging convention

  Tests that depend on this helper should be tagged `@tag :qemu` so
  they skip cleanly when prerequisites are missing
  (`qemu-system-aarch64` not on PATH, or no firmware image built).
  `test/test_helper.exs` is patched by the generator to exclude
  `:qemu` by default.
  """

  require Logger

  defstruct [:port, :node, :tmp_dir]

  @type t :: %__MODULE__{port: port(), node: node(), tmp_dir: String.t()}

  @device_node :"soot-device@127.0.0.1"
  @cookie :my_device_test_cookie

  @doc """
  Returns `:ok` if the prerequisites for `boot/1` are present:
  `qemu-system-aarch64` on PATH and a built firmware image.
  Otherwise returns `{:error, reason}` so test cases can `skip`
  cleanly.
  """
  @spec available?() :: :ok | {:error, term()}
  def available? do
    cond do
      System.find_executable("qemu-system-aarch64") == nil ->
        {:error, :qemu_not_installed}

      firmware_image_path() == nil ->
        {:error, :firmware_not_built}

      true ->
        :ok
    end
  end

  @doc """
  Boots the QEMU image and waits for the device node to register.

  ## Options

    * `:timeout` — milliseconds to wait for distribution; default `60_000`.
    * `:image` — override the firmware image path.
    * `:extra_args` — extra args appended to the qemu command line.
    * `:cookie` — Erlang cookie. Defaults to the module's `@cookie`,
      which the generator sets to match `rel/vm.args.eex`.
    * `:device_node` — node atom to wait for; default
      `:"soot-device@127.0.0.1"`.
  """
  @spec boot(keyword()) :: {:ok, t()} | {:error, term()}
  def boot(opts \\ []) do
    cookie = Keyword.get(opts, :cookie, @cookie)
    device_node = Keyword.get(opts, :device_node, @device_node)

    with :ok <- available?(),
         :ok <- ensure_distribution_running(cookie) do
      image = Keyword.get(opts, :image) || firmware_image_path()
      timeout = Keyword.get(opts, :timeout, 60_000)
      extra = Keyword.get(opts, :extra_args, [])
      tmp = Path.join(System.tmp_dir!(), "soot-qemu-#{System.unique_integer([:positive])}")
      File.mkdir_p!(tmp)

      port = open_port(image, extra)

      case wait_for_node(device_node, timeout) do
        :ok ->
          {:ok, %__MODULE__{port: port, node: device_node, tmp_dir: tmp}}

        {:error, reason} ->
          stop_port(port)
          File.rm_rf!(tmp)
          {:error, reason}
      end
    end
  end

  @doc "Stops the QEMU process and disconnects the device node."
  @spec stop(t()) :: :ok
  def stop(%__MODULE__{port: port, node: node, tmp_dir: tmp}) do
    Node.disconnect(node)
    stop_port(port)
    File.rm_rf!(tmp)
    :ok
  end

  @doc """
  Convenience wrapper for `:rpc.call/4` against the running device.

  Raises `RuntimeError` if the call returns `{:badrpc, _}` so test
  failures point at the actual problem rather than a confusing
  pattern-match failure downstream.
  """
  @spec rpc(t(), module(), atom(), [term()]) :: term()
  def rpc(%__MODULE__{node: node}, mod, fun, args) do
    case :rpc.call(node, mod, fun, args) do
      {:badrpc, reason} ->
        raise "rpc to #{inspect(node)} failed: #{inspect(reason)}"

      result ->
        result
    end
  end

  @doc """
  Returns the absolute path to the latest qemu_aarch64 firmware
  image, or `nil` if no image has been built. Looks in
  `_build/qemu_aarch64_*/nerves/images/`.

  `mix firmware` produces a `.fw` file (an `fwup` archive) — QEMU
  needs a raw disk image. If only the `.fw` exists, this function
  shells out to `fwup -a -t complete -d <name>.img -i <name>.fw`
  to produce one beside it. Subsequent calls reuse the cached
  `.img` until the `.fw` is rebuilt newer than it.
  """
  @spec firmware_image_path() :: String.t() | nil
  def firmware_image_path do
    case latest_image() do
      nil -> maybe_build_image()
      img -> img
    end
  end

  defp latest_image do
    "_build/qemu_aarch64_*/nerves/images/*.img"
    |> Path.wildcard()
    |> latest()
  end

  defp maybe_build_image do
    fw =
      "_build/qemu_aarch64_*/nerves/images/*.fw"
      |> Path.wildcard()
      |> latest()

    cond do
      fw == nil ->
        nil

      System.find_executable("fwup") == nil ->
        nil

      true ->
        fwup_to_img!(fw)
    end
  end

  defp latest([]), do: nil
  defp latest(paths), do: Enum.max_by(paths, &File.stat!(&1).mtime)

  defp fwup_to_img!(fw_path) do
    img_path = Path.rootname(fw_path) <> ".img"

    if File.exists?(img_path) and
         File.stat!(img_path).mtime >= File.stat!(fw_path).mtime do
      img_path
    else
      args = ["-a", "-t", "complete", "-d", img_path, "-i", fw_path]

      case System.cmd("fwup", args, stderr_to_stdout: true) do
        {_, 0} ->
          img_path

        {output, code} ->
          raise "fwup failed (exit #{code}) building #{img_path} from #{fw_path}:\n#{output}"
      end
    end
  end

  defp open_port(image, extra) do
    args =
      [
        "-machine",
        "virt",
        "-cpu",
        "cortex-a72",
        "-smp",
        "2",
        "-m",
        "1024",
        "-nographic",
        "-drive",
        "if=virtio,file=#{image},format=raw",
        "-netdev",
        "user,id=net0,hostfwd=tcp::4369-:4369,hostfwd=tcp::9100-:9100",
        "-device",
        "virtio-net-device,netdev=net0"
      ] ++ extra

    Port.open(
      {:spawn_executable, System.find_executable("qemu-system-aarch64")},
      [:binary, :exit_status, args: args]
    )
  end

  defp stop_port(port) when is_port(port) do
    try do
      Port.close(port)
    rescue
      ArgumentError -> :ok
    end

    :ok
  end

  defp ensure_distribution_running(cookie) do
    if Node.alive?() do
      Node.set_cookie(cookie)
      :ok
    else
      case Node.start(:"soot-device-test-host@127.0.0.1", :longnames) do
        {:ok, _} ->
          Node.set_cookie(cookie)
          :ok

        {:error, reason} ->
          {:error, {:dist_failed, reason}}
      end
    end
  end

  defp wait_for_node(node, timeout) do
    deadline = System.monotonic_time(:millisecond) + timeout
    do_wait_for_node(node, deadline)
  end

  defp do_wait_for_node(node, deadline) do
    if Node.connect(node) == true do
      :ok
    else
      if System.monotonic_time(:millisecond) > deadline do
        {:error, :node_did_not_appear}
      else
        Process.sleep(500)
        do_wait_for_node(node, deadline)
      end
    end
  end
end
