defmodule MyDevice.QEMUTest do
  @moduledoc """
  QEMU integration tests for the device firmware.

  Boots a Nerves QEMU image, connects to it over Erlang distribution,
  and exercises the device application via `:rpc.call/4`. Use these
  tests to verify that the firmware boots, the operator's application
  starts, and the SootDevice DSL module is loaded.

  ## Running

      MIX_TARGET=qemu_aarch64 mix firmware
      mix test --include qemu

  Tests are tagged `@moduletag :qemu` and excluded by default in
  `test/test_helper.exs` so a developer without a built firmware image
  can still run `mix test` cleanly.

  Generated by `mix soot_device.gen.tests`. Operators own this file;
  re-running the generator will not overwrite it.
  """

  use ExUnit.Case, async: false

  @moduletag :qemu

  alias MyDevice.QEMU

  setup do
    case QEMU.available?() do
      :ok ->
        {:ok, qemu} = QEMU.boot(timeout: 90_000)
        on_exit(fn -> QEMU.stop(qemu) end)
        {:ok, qemu: qemu}

      {:error, reason} ->
        {:skip, "qemu unavailable: #{inspect(reason)}"}
    end
  end

  test "device node responds to a remote :erlang.node/0", %{qemu: qemu} do
    assert QEMU.rpc(qemu, :erlang, :node, []) == qemu.node
  end

  test "operator's application is running on the device", %{qemu: qemu} do
    apps = QEMU.rpc(qemu, Application, :started_applications, [])
    assert is_list(apps)
    assert Enum.any?(apps, fn {name, _, _} -> name == :my_device end)
  end

  test "device DSL module is loaded on the device", %{qemu: qemu} do
    assert QEMU.rpc(qemu, Code, :ensure_loaded?, [MyDevice.Device]) == true
  end

  test "device DSL module exposes its compile-time opts on the device", %{qemu: qemu} do
    opts = QEMU.rpc(qemu, MyDevice.Device, :__soot_device_opts__, [])
    assert is_list(opts)
    assert Keyword.has_key?(opts, :contract_url)
    assert Keyword.has_key?(opts, :enroll_url)
    assert Keyword.has_key?(opts, :serial)
  end
end
