defmodule MyDevice.TelemetryTest do
  @moduledoc """
  Exercises the local telemetry path generated by
  `mix soot_device.install --example`:

    * `MyDevice.Telemetry.SystemHealth` samplers (`cpu_sample/0`,
      `memory_sample/0`, `disk_sample/0`) return shape-correct maps.
    * Pushing those samples through
      `SootDeviceProtocol.Telemetry.Pipeline.write/3` emits
      `[:soot_device, :pipeline, :write]` `:telemetry` events with
      the documented measurements + metadata.
    * With the `SootDeviceProtocol.Telemetry.Buffer.Duxedo` backend
      configured, written samples land in DuckDB and are queryable
      back out via `Duxedo.Streams.take_oldest/3` — the canonical
      "local capture and query" path on a device.

  Generated by `mix soot_device.gen.tests`. Operators own this file;
  re-running the generator will not overwrite it.

  Skipped on non-Linux hosts (the SystemHealth samplers depend on
  `/proc` and `:os_mon`).
  """

  use ExUnit.Case, async: false

  alias MyDevice.Telemetry.SystemHealth
  alias SootDeviceProtocol.Storage
  alias SootDeviceProtocol.Telemetry.Buffer
  alias SootDeviceProtocol.Telemetry.Pipeline

  @cpu_schema [
    {:seq, :s64},
    {:load_1m, :f64},
    {:load_5m, :f64},
    {:load_15m, :f64},
    {:user_pct, :f64},
    {:system_pct, :f64},
    {:iowait_pct, :f64}
  ]

  setup do
    if File.exists?("/proc/loadavg") do
      :ok
    else
      {:skip, "SystemHealth samplers require /proc — skipped on this host"}
    end
  end

  describe "system health samplers" do
    test "cpu_sample/0 returns a map with load + utilization keys" do
      sample = SystemHealth.cpu_sample()
      assert is_map(sample)
      # Linux fills these from /proc/loadavg + :cpu_sup.util.
      assert Map.has_key?(sample, :load_1m)
      assert Map.has_key?(sample, :load_5m)
      assert Map.has_key?(sample, :load_15m)
    end

    test "memory_sample/0 returns total/available/used bytes" do
      sample = SystemHealth.memory_sample()
      assert is_map(sample)
      assert is_integer(sample[:total_bytes])
      assert is_integer(sample[:available_bytes])
      assert is_integer(sample[:used_bytes])
    end

    test "disk_sample/0 returns mount metadata" do
      sample = SystemHealth.disk_sample()
      assert is_map(sample)
      # `:disksup` may not have classified the root mount on all
      # hosts; only assert when the sampler returned data.
      if sample != %{} do
        assert sample[:mount_point] == "/"
        assert is_integer(sample[:total_bytes])
      end
    end
  end

  describe ":telemetry events from Pipeline.write" do
    setup do
      pipeline = start_memory_pipeline!()

      ref = make_ref()

      :ok =
        :telemetry.attach(
          ref,
          [:soot_device, :pipeline, :write],
          &__MODULE__.send_event/4,
          %{pid: self()}
        )

      on_exit(fn -> :telemetry.detach(ref) end)

      {:ok, pipeline: pipeline}
    end

    test "writing a cpu sample emits a write event with bytes + stream + seq", %{
      pipeline: pipeline
    } do
      assert {:ok, seq} = Pipeline.write(pipeline, "cpu", SystemHealth.cpu_sample(), [])

      assert_receive {:telemetry, [:soot_device, :pipeline, :write], measurements, metadata},
                     1_000

      assert is_integer(measurements.bytes) and measurements.bytes > 0
      assert metadata.stream == "cpu"
      assert metadata.seq == seq
    end

    test "memory and disk streams emit their own events", %{pipeline: pipeline} do
      assert {:ok, _} = Pipeline.write(pipeline, "memory", SystemHealth.memory_sample(), [])
      assert_receive {:telemetry, [:soot_device, :pipeline, :write], _, %{stream: "memory"}}, 1_000

      assert {:ok, _} = Pipeline.write(pipeline, "disk", SystemHealth.disk_sample(), [])
      assert_receive {:telemetry, [:soot_device, :pipeline, :write], _, %{stream: "disk"}}, 1_000
    end
  end

  describe "local capture + query through Duxedo" do
    # Synthetic fixture rather than `SystemHealth.cpu_sample/0`:
    # `:cpu_sup.util/1` returns `0` on its first call (a priming
    # read), so the real sampler omits the `_pct` keys until the
    # second tick. Duxedo's strongly-typed schema rejects the
    # half-populated map. The fixture exercises the full Duxedo
    # round-trip without depending on `:cpu_sup` warm-up timing.
    @cpu_fixture %{
      load_1m: 0.42,
      load_5m: 0.31,
      load_15m: 0.27,
      user_pct: 12.5,
      system_pct: 4.0,
      iowait_pct: 0.5
    }

    setup do
      ensure_duxedo!()
      pipeline = start_duxedo_pipeline!()
      {:ok, pipeline: pipeline}
    end

    test "samples written to the pipeline land in Duxedo and are queryable", %{
      pipeline: pipeline
    } do
      assert {:ok, seq} = Pipeline.write(pipeline, "cpu", @cpu_fixture, [])

      # Query Duxedo directly — proves the data is captured locally
      # AND retrievable without the upload path. `take_oldest/3` is
      # the same surface the upload-via-Arrow code uses.
      assert {:ok, rows} =
               Duxedo.Streams.take_oldest(:cpu, 10, instance: duxedo_instance())

      assert is_list(rows) and rows != []
      assert Enum.any?(rows, &(&1[:seq] == seq))

      [%{} = first | _] = rows
      assert is_float(first[:load_1m])
      assert is_float(first[:user_pct])
    end

    test "Duxedo.Streams.stats/2 reports the captured row count", %{pipeline: pipeline} do
      assert {:ok, _} = Pipeline.write(pipeline, "cpu", @cpu_fixture, [])
      assert {:ok, _} = Pipeline.write(pipeline, "cpu", @cpu_fixture, [])

      {:ok, %{rows: rows}} = Duxedo.Streams.stats(:cpu, instance: duxedo_instance())
      assert rows >= 2
    end
  end

  ## ────────────────────────────────────────────────────────────────────
  ## Helpers
  ## ────────────────────────────────────────────────────────────────────

  defp start_memory_pipeline! do
    {:ok, storage} = Storage.Memory.open()

    start_supervised!(
      {Pipeline,
       [
         base_url: "http://localhost",
         storage: storage,
         streams: [
           {"cpu", %{fingerprint: "test-cpu", ingest_endpoint: "/ingest/cpu"}},
           {"memory", %{fingerprint: "test-memory", ingest_endpoint: "/ingest/memory"}},
           {"disk", %{fingerprint: "test-disk", ingest_endpoint: "/ingest/disk"}}
         ],
         auto_flush?: false,
         name: nil
       ]}
    )
  end

  defp start_duxedo_pipeline! do
    {:ok, storage} = Storage.Memory.open()
    duxedo_handle = Buffer.Duxedo.open!(instance: duxedo_instance())

    start_supervised!(
      {Pipeline,
       [
         base_url: "http://localhost",
         storage: storage,
         buffer: {Buffer.Duxedo, duxedo_handle},
         streams: [
           {"cpu",
            %{
              fingerprint: "test-cpu",
              ingest_endpoint: "/ingest/cpu",
              schema: @cpu_schema
            }}
         ],
         auto_flush?: false,
         name: nil
       ]}
    )
  end

  defp ensure_duxedo! do
    persistence_dir =
      Path.join(
        System.tmp_dir!(),
        "duxedo_telemetry_test_#{System.unique_integer([:positive])}"
      )

    File.mkdir_p!(persistence_dir)
    on_exit(fn -> File.rm_rf!(persistence_dir) end)

    start_supervised!(
      {Duxedo,
       [
         instance: duxedo_instance(),
         persistence_dir: persistence_dir,
         flush_interval: 60,
         collect_interval: 60
       ]}
    )

    :ok
  end

  # Per-test instance keeps tests isolated from each other's tables.
  defp duxedo_instance do
    String.to_atom("duxedo_test_#{:erlang.phash2(self())}")
  end

  # `:telemetry.attach/4` warns when handed a local-function capture
  # (`&send_event/4`) — module-qualified is the recommended form.
  @doc false
  def send_event(event, measurements, metadata, %{pid: pid}) do
    send(pid, {:telemetry, event, measurements, metadata})
  end
end
